# Change these first
owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Online Chat
    url: https://example.koj.co
  - name: ping ip
    check: "tcp-ping"
    url: 165.84.188.86
    port: 20
  - name: port 9443
    check: "tcp-ping"
    url: 165.84.188.81
    port: 9443
  - name: alarm
    check: "tcp-ping"
    url: 165.84.188.86
    port: 1052
  - name: ping port
    check: "tcp-ping"
    url: 165.84.188.81
    port: 19005
  - name: Self-signed SSL
    url: https://165.84.188.81:19005/login
    __dangerous__insecure: true
  - name: Login API
    method: POST
    url: https://uptimerobot.com/login
    headers:
      - "Content-Type: application/json"
    body: '{ "userEmail1": "hello","userPassword": "1234" }'

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: demo.upptime.js.org
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
